### ISSUE TITLE
Scan enqueued scripts for cookies in TIKI WooCommerce

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#19]
TIKI WooCommerce plugins should be able to track scripts added by WordPress plugins and themes that may set cookies. This can be achieved by creating a function that loads and reads the enqueued JS scripts as plain text files and searches for any set cookie methods.

Once the scripts and their cookie setters are identified, they should be saved to be displayed to the user in the Dashboard. 

### Tasks
- [ ] Create the method to scan the scripts in both TIKI WooCommerce plugins
- [ ] Create a Custom Post Type (model) to save the scripts and their cookies (Services)
- [ ] Create the categories for the Services

**Comment by ricardobrg** [comment]
Moved to a different direction. See #18
