### ISSUE TITLE
Scan post content for script tags that set cookies

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#21]
To enhance the cookie compliance feature in TIKI WooCommerce plugins, it needs to scan all posts, as a script can be added in WordPress using the recommended enqueue script method or by copying/pasting its contents in the post. 

The goal is to identify any cookie setters in the posts, add them to the Services, and remove them from the post if the user does not give consent.

This method should be hooked to the save post method and have an optional daily cron.

### Tasks
- [ ] Create the method to scan the posts
- [ ] Extract the scripts and save them as Services
- [ ] Remove the scripts to which the user did not consent.

**Comment by ricardobrg** [comment]
Moved to a diffrent direction. See #18
