### ISSUE TITLE
Create Flutter admob example

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#3]
As a developer working with TIKI SDK, I need to implement AdMob rewarded ads using TIKI SDK. 

This example will show how to do it. 

The initial screen of the app will have 1 button: Show Rewarded Ad.

- Create a "Show Rewarded Ad" button on the main screen of the app.
- When the user taps on the "Show Rewarded Ad" button, show the a license prompt offer with the TIKI SDK `present()` method.
- If the user opts into the offer, show the rewarded ad.
  - After the rewarded ad is shown, redirect the user to the reward screen that displays the simple text "Rewarded!".
- If the user doesn't opt in, take it back to the home screen.

### Tasks
- [x] Create a new Flutter App in the flutter/admob folder. The app package should be com.mytiki.example.admob
- [x] Create the home and reward screens
- [x] Show the reward screen when user taps the Show Rewarded Ad button
- [x] Implement [Flutter AdMob](https://pub.dev/packages/google_mobile_ads)
- [x] Show a rewarded ad before the reward screen.
- [x] Implement [TIKI SDK Flutter](https://github.com/tiki/tiki-sdk-flutter)
- [x] Use the TIKI SDK `present` method to show the offer prompt when user taps the button
- [x] Use the TIKI SDK `onAccept` callback to show the rewarded ad after the user opt in
- [x] Use the TIKI SDK `guard` method to check if the user already opted in and show the rewarded ad in subsequent button taps.

**Comment by ricardobrg** [comment]
Maybe the logic can be all done in this issue. I just separated the tasks to make sure this issue is not too big and some implementation of the admob blocks it.

**Comment by ricardobrg** [comment]
Updated the issue to simplify the example.

**Comment by ricardobrg** [comment]
@harshit933 will work on this
