### ISSUE TITLE
Implement Example of Handling User Consent with TIKI for Google Tag

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#40]
I want to provide a working example of how to handle user consent with TIKI for Google Tag,
So that other developers can easily implement it by copying and pasting a small JavaScript snippet.

### Tasks
- [ ] Write Sample Code for User Consent Handling. A small JavaScript snippet that can be easily copied and pasted by developers who use gtag.js.
- [ ] Implement logic to check the validity of the license on page load and update the gtag APIs accordingly.
- [ ] Test the sample code with a live website
- [ ] Write the docs

**Comment by ricardobrg** [comment]
not planned
