### ISSUE TITLE
Shopify: create the user discount code on license acceptance

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#42]
As a developer, I need to create a callback function for TIKI SDK license acceptance, so that a discount code can be created using the TIKI user ID.

### Tasks

- [ ] Create Discount Code with TIKI User ID
- [ ] Handle Denial Callback and Remove Discount Code
- [ ] Verify User's Email for Discount Code Usage
- [ ] Automatically apply  Discount Code in Cart
- [ ] Check License Validity prior to Discount Code Creation

Resouces
https://shopify.dev/docs/api/admin-rest/2023-01/resources/discountcode
https://shopify.dev/docs/apps/custom-data/metafields#developer-resources
