### ISSUE TITLE
Override cookie yes banner for Shopify

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#43]
To properly handle auto-blocking of unwanted cookies, the TIKI Shopify App will use the Cookie Yes integration.

Since it already has an app for Shopify, we will block their banner and show ours instead. 

### Tasks
- [ ] check if cookie yes app is installed
- [ ] set the cookie to not show the banner
- [ ] show the banner if the user decline the offer
- [ ] call their accept all callback if the user accepts the offer

**Comment by ricardobrg** [comment]
cookie yes integration with shopify is done using the script as a vanilla JS integration. This issue is not applicable for Shopify specifically.
