### ISSUE TITLE
Create UI options in app theme extension

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#55]
As a developer,
I want to config TIKI SDK pre built UI options in the app theme editor,
So that administrators can easily configure the colors and fonts for the TIKI SDK's pre-built UI.

## Description

We need to provide a way for administrators to customize the UI elements, such as colors and fonts, for the pre-built UI components. This customization should be done within the app theme extension editor in Shopify, allowing administrators to preview and apply the changes in realtime.

## Acceptance Criteria

1. The app theme extension should provide the default Shopify interface for customizing the colors and the font used in pre built UI.
2. While in the theme editor, the user can check a preview checkbox that will trigger TikiSdk.present() and show the UI for preview. A default user id should be used to prevent the creation of test users.

## Tasks

- [x] Set up the app theme extension development environment in Shopify.
- [x] Design and implement the UI options for the TIKI SDK customization within the app theme extension editor.
- [x] Provide color customization options, allowing administrators to select and define colors for different UI elements.
- [x] Implement font customization options, allowing administrators to specify the font family.
- [x] Add the preview checkbox to see the result of the options in the screen (may be a button too).

**Comment by ricardobrg** [comment]
![Image](https://github.com/tiki/integrations/assets/8357343/31768f28-258a-407b-8f16-89086f6b8861)
