### ISSUE TITLE
Use Shopify customer ID as TIKI user ID

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#58]
As a developer,
I want to present the TIKI UI and save the user's decision in cookies,
So that I can create a TIKI license when the user logs into Shopify.

## Description
The TIKI app should present the UI without initializing the TIKI SDK when a user visits the store and is not logged in.
The user's decision regarding the Offer should be saved in cookies.

When the user logs into Shopify, the app should initialize the TIKI SDK with the Shopify customer id as TIKI user ID.

When the TIKI SDK is initialized, the app should create a TIKI License Record with the appropriate use case (no use cases if denied, attribution use case if allowed).

If the app is installed in a store with already logged-in users, the TIKI SDK should be initialized on their first visit with their Shopify customer ID, and create the license with their decision.

## Tasks
- [x] Implement the TIKI UI presentation without initializing the TIKI SDK for non-logged-in users.
- [x] Save the user's decision regarding TIKI in cookies.
- [x] Check the user's decision in the cookies when the user logs into Shopify.
- [x] Initialize the TIKI SDK and provide the Shopify customer id as the TIKI user id,
- [x] Create a TIKI license record with the appropriate use case based on the user's decision (no use cases if denied, attribution use case if allowed).
- [x] Initialize the TIKI SDK on the first visit for already logged-in users, and present them with the Offer.
