### ISSUE TITLE
Create a webhook to send all completed orders to TIKI servers

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#63]
As a developer,
I want to create a webhook that sends all completed orders to TIKI servers,
So that TIKI can receive receipt data when the merchant decides to send it for royalties.

## Description
The TIKI app should subscribe to the Shopify `orders/paid` webhook event. When an order is marked as paid in Shopify, the webhook should be triggered. The app should send the Order object data to a custom URL which saves the Order data for debugging. After the backend implementation is done, this URL should be replaced by the TIKI backend URL.

In the app settings a new option should be added, so merchants can start sending their shop data to TIKI. For this story, the webhook should just consider a boolean variable that will be set in this option. The admin UI and related documentation and enforcements in the terms of the Offer should be done in another story.

## Tasks
- [x] Implement the webhook subscription to the Shopify `orders/paid` event in 
- [x] Receive the Order object and send it to a custom URL as JSON.
- [ ] Test the webhook by marking an order as paid in a TIKI dev Shopify store and verifying that the data is sent to the custom URL.
- [ ] Implement error handling and retry mechanisms in the webhook to handle any failures or errors in sending the data.
- [ ] Check a boolean value before sending the data. It will be linked with Admin options to make sure the merchant opted in to send data.

**Comment by ricardobrg** [comment]
note: 
check event instead

**Comment by ricardobrg** [comment]
update the subscription for #70

**Comment by ricardobrg** [comment]
replaced by #75
