### ISSUE TITLE
Shopify app theme block settings

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#64]
As a merchant using the TIKI Shopify app,
I want to control all the app options from the app embed UI,
So that I can control the integration with TIKI in one place.

## Description
1. The TIKI Shopify app embed UI should include: 
- The UI options for the banner
- The Offer options for the user: reward image, use cases, terms and description
- The configuration of the discount (percentage, value and usage limits)

## Tasks
- [ ] add UI options for the banner
- [ ] add Offer options for the user: reward image, use cases, terms and description
- [ ] add configuration of the discount (percentage, value and usage limits)
