### ISSUE TITLE
Integrate the TIKI SDK into discount

### ISSUE THREAD

**Issue by ricardobrg** [tiki/integrations#66]
As a developer,
I want to check if a user has a valid TIKI license,
So that I can automatically apply discounts to Shopify customers who have a valid license.

## Description

To ensure that discounts are applied only to customers with a valid TIKI license, we need to call the TIKI API to check the license status. The goal is to automatically apply discounts to Shopify customers who have a valid license associated with their account.

## Tasks
- [ ] The system should check the validity of a user's TIKI license before applying discounts.
- [ ] Discounts should be automatically applied only to Shopify customers who have a valid TIKI license.
- [ ] The license check should be performed using the TIKI API

**Comment by ricardobrg** [comment]
Updated by #70 

Not applicable.
The discount information will be saved in user meta fields. It will be used in #71 to apply the discounts.
